#!/bin/sh
set -e

CONFIG_DIR="/etc/beacon-agent"

if [ "$1" = "remove" ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'beacon-agent.service' >/dev/null || true
	fi
  if [ -d "$CONFIG_DIR" ]; then
      rm -rf "$CONFIG_DIR"
      echo "Configuration directory removed from $CONFIG_DIR"
  fi
fi

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
		# Remove __pycache__ directories for the installed package
    find /usr/lib/python3/dist-packages/beacon_agent -type d -name '__pycache__' -exec rm -rf {} +
fi

exit 0